---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: nextcloud-data-pvc
    namespace: nextcloud
  hostPath:
    path: /var/lib/k8s/volumes/nextcloud-data-pv